### ISSUE TITLE
I cant get the loot collector to work

### ISSUE THREAD

**Issue by TheLostWrld** [aa3615058/Lengyu-BL2-sdk-Mods#1]
It doesnt work for me i downladed it and it doesnt work

**Comment by aa3615058** [comment]
> It doesnt work for me i downladed it and it doesnt work

What? I tested it and It worked well. Did you install the SDK properly and enable the mod in the menu "MODS" ?

**Comment by aa3615058** [comment]
> It doesnt work for me i downladed it and it doesnt work

Please take a look at this. https://bl-sdk.github.io/
