### ISSUE TITLE
Shop Reseter not working

### ISSUE THREAD

**Issue by ghost** [aa3615058/Lengyu-BL2-sdk-Mods#2]
I have made sure that the mod files are installed correctly and have enabled it in the mod menu. When I press F9, shops don't reset and nothing happens. Do you know what might be the issue?

**Comment by aa3615058** [comment]
> I have made sure that the mod files are installed correctly and have enabled it in the mod menu. When I press F9, shops don't reset and nothing happens. Do you know what might be the issue?

Well... I see... I will update the description of this mod. Please try to first quit the vending machine interface and then press F9.

**Comment by aa3615058** [comment]
> I have made sure that the mod files are installed correctly and have enabled it in the mod menu. When I press F9, shops don't reset and nothing happens. Do you know what might be the issue?

OMG, I found a foolish bug. Now I have fixed it and updated files. Please download it again. Thanks for your report!

**Comment by ghost** [comment]
Hi, yes it is working now. Thanks for your help! I'm glad you managed to find the bug :)
