### ISSUE TITLE
Not Downloading Correctly

### ISSUE THREAD

**Issue by ZingierMold4** [aa3615058/Lengyu-BL2-sdk-Mods#3]
When I donwload the mod from link on the PythonSDK website (https://bl-sdk.github.io/mods/LootCollector/) the zip file only contains the "__init__.py" file, none of the other files for the mod. I dont know if that's all there's supposed to be, but it's done this with several other mods too, and I'd really like to know if there's a way that I can find a solution to this issue. Maybe someone can just email me the complete mod folder and I can download it from there. Or if someone could tell me what I'm doing wrong and show me the correct steps to take to install it and get it working properly.
![LootCollector SS](https://github.com/user-attachments/assets/18035eae-e718-4b31-99d6-035ba03483c0)
 Any help would be appreciated, thanks.

**Comment by aa3615058** [comment]
> When I donwload the mod from link on the PythonSDK website (https://bl-sdk.github.io/mods/LootCollector/) the zip file only contains the "**init**.py" file, none of the other files for the mod. I dont know if that's all there's supposed to be, but it's done this with several other mods too, and I'd really like to know if there's a way that I can find a solution to this issue. Maybe someone can just email me the complete mod folder and I can download it from there. Or if someone could tell me what I'm doing wrong and show me the correct steps to take to install it and get it working properly. ![LootCollector SS](https://private-user-images.githubusercontent.com/81852468/351284610-18035eae-e718-4b31-99d6-035ba03483c0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Mzk5MTEsIm5iZiI6MTcyMjQzOTYxMSwicGF0aCI6Ii84MTg1MjQ2OC8zNTEyODQ2MTAtMTgwMzVlYWUtZTcxOC00YjMxLTk5ZDYtMDM1YmEwMzQ4M2MwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1MjY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmY3NzVjM2EyYTlhNmQ1MDUyZTkzNDlhZjgwMzBhNDk3N2VjZGE4M2NiNTRhODZmYzc5ZGUwMTgxZTJmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKjnbp1fREAojW5VokJTnzKqLbuZAKIF7HkF9GAofkw) Any help would be appreciated, thanks.

Now I have updated the zip files. They will contain a seperate mod folder. Just put the folder "LootCollector" into the folder Borderlands2\Binaries\Win32\mods then it will work. Sorry for confusing you, have a nice game. :)
