### ISSUE TITLE
[Loot Collector] Add support for The Pre-Sequel

### ISSUE THREAD

**Issue by ghost** [aa3615058/Lengyu-BL2-sdk-Mods#4]
This mod is fantastic, it's better than [Be Gone Out Of Bounds Loot](https://bl-sdk.github.io/mods/BeGoneOutOfBoundsLoot/) because you can see the items, the only thing it lacks is support for The Pre-Sequel, so please add support for The Pre-Sequel.

**Comment by SaNyaZXC666** [comment]
Yes, please add support for TPS :)

**Comment by aa3615058** [comment]
> This mod is fantastic, it's better than [Be Gone Out Of Bounds Loot](https://bl-sdk.github.io/mods/BeGoneOutOfBoundsLoot/) because you can see the items, the only thing it lacks is support for The Pre-Sequel, so please add support for The Pre-Sequel.

OK, now LootCollector supports TPS. Have a nice game :)
